### PR TITLE
Pin dask to 2.20.0

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Review by rikturr — APPROVED** [review]

**Review by jameslamb — CHANGES_REQUESTED** [review]
why are we pinning to a specific version instead of using floors and ceilings? Is there a specific thing in newer versions of `distributed` that break `dask-saturn`? I feel like maybe I missed a conversation.

**Comment by jsignell** [comment]
@jameslamb so you'd prefer a ceiling?

**Comment by jameslamb** [comment]
> @jameslamb so you'd prefer a ceiling?

Yep! I'd rather have >=2.20.0,<2.25.0 (or whatever ceiling we know introduced the problem), if we know the ceiling.

Pinning to one specific version is fine for images but I feel strongly that libraries should not do that. That's especially true for something as central as `distributed`.

Other libraries that are likely to be used with `dask-saturn` have their own requirements for `distributed`, and a specific pin increases the likelihood that we'll conflict with them in the future (even if `==2.2.0.0` doesn't conflict with them today). For example:

* `dask-xgboost`: [>= 1.15.2](https://github.com/dask/dask-xgboost/blob/master/requirements.txt#L3)
* `prefect`: [>= 2.15.0](https://github.com/PrefectHQ/prefect/blob/c3eb320ac3d108edd132bceab4dcf5451335e54e/requirements.txt#L5)
* `dask-ml`: [>= 2.4.0](https://github.com/dask/dask-ml/blob/4805ce2fa0e1c093b085f319dac4ef6b9cc4d4b5/setup.py#L15)

**Comment by jsignell** [comment]
I can't reproduce any odd widget behavior @rikturr. So I'm going to release this without this PR.

**Comment by rikturr** [comment]
Okay, I'll try on my end too and if I can get a reproducible example I'll re-open this

**Pull request closed without merging**
