### PR TITLE
Register plugin after start

### PR DESCRIPTION
**Pull request by jsignell**
Ok so new approach, do the work in dask-saturn. To test this out make a new image with pip requirements like:

```
dask[complete]
git+https://github.com/saturncloud/dask-saturn.git@jsignell/register-plugin
```

Create a project with that image, open a notebook and run:
```python
from dask_saturn import SaturnCluster
from dask.distributed import Client

import pandas as pd
import dask.dataframe as dd

cluster = SaturnCluster(n_workers=1)
client = Client(cluster)

df = pd.DataFrame({'df': [1,2,3]})
ddf = dd.from_pandas(df, npartitions=1)
ddf = ddf.persist()

def helper2(fut):
    return fut.compute()
fut2 = client.submit(helper2, ddf)
fut2.result()
```

### CODE REVIEW

**Comment by jsignell** [comment]
This will work either with the cluster object

```python
from dask_saturn import SaturnCluster
from distributed import Client

cluster = SaturnCluster()
client = Client(cluster)
```

Or by just importing the plugin and registering it on the client in the notebook:

```python
from dask_saturn import SaturnSetup
from distributed import Client

client = Client("tcp://d-admin-dask.main-namespace:8786")
client.register_worker_plugin(SaturnSetup())
```

**Comment by bhperry** [comment]
I got this error when running the example you provided:
```
ValueError: Inputs contain futures that were created by another client.
```

**Comment by jsignell** [comment]
@bhperry Did you have this version of dask-saturn installed?

**Comment by bhperry** [comment]
> @bhperry Did you have this version of dask-saturn installed?

I thought I did, but now I'm realizing I added a regular `dask-saturn` requirement about the git ref for some reason, so it probably installed the wrong version. Trying again.

**Comment by jsignell** [comment]
Closes CU-e0vwea

**Comment by hhuuggoo** [comment]
Task linked: [CU-e0vwea Futures cannot be unpickled on dask workers](https://app.clickup.com/t/e0vwea)

**Review by bhperry — APPROVED** [review]
Example worked once I installed the right version of dask-saturn

LGTM

**Pull request merged**
