### PR TITLE
Append cwd to python path in worker plugin

### PR DESCRIPTION
**Pull request by jsignell**
This will resolve Module Not Found issues when the user syncs files to the workers.

To try this out we'll set up a project like

```
/home/jovyan/project/
|---- util/
|   |---- __init__.py
|   |---- hello.py
|
|---- Untitled.ipynb
```

Where hello.py is like:
```python
# util/hello.py
def greet():
    return "Hello"
```

Then within the notebook do:

```python
import dask
from distributed import Client
from dask_saturn import SaturnCluster, RegisterFiles, sync_files

# function from custom module
from util.hello import greet 

cluster = SaturnCluster()
client = Client(dask_cluster)
client.register_worker_plugin(RegisterFiles())
sync_files(client, "util")

# restart the workers so they will see the changes
dask_client.restart()

greet_task = dask.delayed(greet)()
dask.compute(greet_task)
```

### CODE REVIEW

**Review by jameslamb — COMMENTED** [review]
TIL `sys.path`, cool!

Will this be broken if someone changes working directories in their code after importing but before setting up their `SaturnCluster`?

If yes, would it be too weird to somehow pass in a module object instead, and then use that module's `.__path__`?

**Comment by jsignell** [comment]
> Will this be broken if someone changes working directories in their code after importing but before setting up their `SaturnCluster`

That's an interesting idea. I don't know how you would be able to do that on your worker.

**Comment by jameslamb** [comment]
> > Will this be broken if someone changes working directories in their code after importing but before setting up their `SaturnCluster`

Would this actually break? Or have I misunderstood?

If it would but you're not too worried about it, I'm fine with this PR as-is and we can do the more complicated thing if it becomes a problem.

**Comment by jsignell** [comment]
I don't think there is any way that you could do that. The dask worker doesn't exist until you create the cluster and when you create the cluster the plugin registers itself and runs on every worker. You would have to do something very strange to get in the situation that you are talking about, so I don't feel worried about it.

**Comment by jameslamb** [comment]
> I don't think there is any way that you could do that. The dask worker doesn't exist until you create the cluster and when you create the cluster the plugin registers itself and runs on every worker. You would have to do something very strange to get in the situation that you are talking about, so I don't feel worried about it.

ok cool

**Review by jameslamb — APPROVED** [review]

**Pull request merged**
